when@test:
  doctrine:
    dbal:
      connections:
        default:
          driver: "pdo_sqlite"
          dbname: ":memory:"
          use_savepoints: true

  dama_doctrine_test:
    enable_static_connection: true
    enable_static_meta_data_cache: true
    enable_static_query_cache: true
