# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: { url: "%env(ELASTICSEARCH_URL)%" }
  indexes:
    products:
      properties:
        title: { type: text }
        description: { type: text }
      persistence:
        driver: orm
        model: App\Entity\Product
        provider: ~
        finder: ~
