security:
  # password_hashers:
  #   Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  password_hashers:
    App\Entity\User:
      algorithm: bcrypt

  # csrf_protection:
  #   enabled: true

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      entry_point: App\Security\LoginFormAuthenticator
      stateless: false
      logout:
        path: app_logout
        target: app_login
      remember_me:
        secret: "%env(COOKIE_TOKEN)%"
        signature_properties: ["password", "updatedAt"]
        lifetime: 604800 # 7 Tage
        path: /
        name: stay_in_shop
        secure: false
        httponly: true
        samesite: lax # Überlege 'lax' als Alternative zu 'strict'

  access_control:
    - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/users, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/product/insert, roles: ROLE_ADMIN }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  # session_fixation_strategy: none
  # erase_credentials: false

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
