controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_verify_email:
  path: /verify/{token}/{email}
  controller: App\Controller\AuthController::verify
  methods: [GET]
